namespace FindTheWords
{
    partial class Form1
    {
        /// <summary>
        ///Gerekli tasarımcı değişkeni.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///Kullanılan tüm kaynakları temizleyin.
        /// </summary>
        ///<param name="disposing">yönetilen kaynaklar dispose edilmeliyse doğru; aksi halde yanlış.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer üretilen kod

        /// <summary>
        /// Tasarımcı desteği için gerekli metot - bu metodun 
        ///içeriğini kod düzenleyici ile değiştirmeyin.
        /// </summary>
        private void InitializeComponent()
        {
            this.listBox1 = new System.Windows.Forms.ListBox();
            this.textBox1 = new System.Windows.Forms.TextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.textBox2 = new System.Windows.Forms.TextBox();
            this.listBox2 = new System.Windows.Forms.ListBox();
            this.SuspendLayout();
            // 
            // listBox1
            // 
            this.listBox1.FormattingEnabled = true;
            this.listBox1.ItemHeight = 26;
            this.listBox1.Items.AddRange(new object[] {
            "A / a",
            "Actor: Aktör (ektır)",
            "Archaeologist: Arkeolog (arkiyalojıst)",
            "Architect: Mimar (arkitekt)",
            "Accountant: Muhasebeci (ekavnınt)",
            "Author: Yazar (avtır)",
            "Alligator: Timsah (eligeytır)",
            "Aunt: Hala/Teyze (eunt)",
            "Answer: Cevap (ensvır)",
            "After: Sonra (aftır)",
            "Approve: Onaylamak (apruuv)",
            "Adore: Hayranlık duymak (edoor)",
            "Alien: Uzaylı (eliyın)",
            "Adjective: Sıfat (acektiv)",
            "Arrive: Varmak, ulaşmak (errayv)",
            "Accomplish: Başarmak, tamamlamak (akomplış)",
            "Assume: Farz etmek (asûm)",
            "Accommodation: Konaklama (ekomodeyşın)",
            "Accident: Kaza (eksidınt)",
            "Attention: Dikkat, özen (atenşın)",
            "At the moment: Şu an (et dı momınt)",
            "Acceleron: İvme (ekselıran)",
            "Adult: Yetişkin (edalt)",
            "Abdomen: Karın (ebdımın)",
            "Abate: Azaltmak, hafifletmek (abeyt)",
            "Affect: Etkilemek (afect)",
            "Accept: Kabul etmek (ıksept)",
            "Anger: Öfke (engır)",
            "Angry: Kızgın (engriy)",
            "Absolute: Kesin, tam, mutlak (ebsuluvt)",
            "Absolutely: Kesinlikle",
            "Ability: Kabiliyet (ebılidy)",
            "Amusement: Eğlence (emiyusmınt)",
            "Abhor: Nefret etmek (ebhoor)",
            "Additive: Katkı (edıtiv)",
            "Actual: Gerçek (ekşııl)",
            "Adjust: Ayarlamak (edcast)",
            "Advice: Tavsiye (edvays)",
            "Archipelago: Takımadalar (arkıpelago)",
            "Abrupt: Ani, beklenmedik (ıbrapt)",
            "About: Zarf iken: Aşağı yukarı, yaklaşık / Edat iken: Hakkında, ilgili (ebavt)",
            "Avenue: Bulvar (evinyuu)",
            "Ancient: Antik (eyncınt)",
            "Almond: Badem (almınd)",
            "Against: Karşı, aleyhinde (egenst)",
            "Again: Bir daha (egeyn)",
            "Adverse: Kötü, elverişsiz (edvörs)",
            "Adventure: Macera (edvençır)",
            "Action: Hareket, eylem (ekşın)",
            "Accident: Kaza, kötü olay (eksidınt)",
            "Article: Makale (artikıl)",
            "Articles: Nesne (artikıls)",
            "Absent: Yok (ebsınt)",
            "Accommodation: Konaklama, kalacak yer (ekomodeyşın)",
            "Advert: İlan, duyuru (edvört)",
            "Apprentice: Çırak, acemi (eprentıs)",
            "At least: En azından, bari (et liist)",
            "Avoid: Kaçınmak (evoyd)",
            "Anymore: Artık, bundan sonra (enimoor)",
            "Assurance: Sigorta, güvence",
            "Arrogant: Kibirli",
            "Accelerate: Hızlandırmak",
            "Admit: İtiraf etmek",
            "Aspect: Görünüş",
            "Advertiser: Reklamcı (edvırtayzır)",
            "Authority: Yetki",
            "Attempt: Girişim, denemek, teşebbüs",
            "Attach: Yapıştırmak, eklemek, iliştirmek, tutturmak",
            "Abolish: Feshetmek",
            "Appear: Görünmek",
            "Agriculture: Tarım",
            "Accustom: Alıştırmak",
            "Academy: Akademi",
            "Approach: Yaklaşmak",
            "Absence: Yokluk",
            "Already: Zaten",
            "Allow: İzin vermek",
            "Agreement: Anlaşma",
            "Audience: Seyirci",
            "Argue: Tartışmak",
            "Among: Arasında",
            "Although: Rağmen",
            "Architecture: Mimari",
            "Aisle: Koridor",
            "Actual: Güncel",
            "Actually: Aslında",
            "Arrest: Tutuklamak",
            "Alert: Uyarmak",
            "Advice: Tavsiye",
            "Anyway: Her neyse",
            "Apartmant: Daire",
            "Attic: Çatı katı / Çatı odası",
            "Armchair: Koltuk (tekli)",
            "Adviser: Danışman, akıl hocası",
            "Adhere: Yapışmak, bağlı kalmak",
            "Allude: İma etmek, kastetmek",
            "Add: Eklemek",
            "Achieve: Elde etmek, başarmak",
            "Almost: Neredeyse",
            "Accurate: Doğru / Kesin",
            "Account: Hesap",
            "Arrange: Düzenlemek / Ayarlamak",
            "Appreciate: Memnun olmak",
            "Absurd: Absürt / Saçma / Uygunsuz",
            "Abroad: Yurt dışı",
            "Access: Erişim",
            "Accuse: Suçlamak",
            "Aggression: Saldırganlık",
            "Awful: Berbat",
            "B / b ",
            "Barman: Barmen (barmın)",
            "Barber: Berber (barbır)",
            "Baker: Fırıncı (beykır)",
            "Businessman: İş adamı (biznısmen)",
            "Butcher: Kasap (baçır)",
            "Blue: Mavi (blu)",
            "Brown: Kahverengi (bravn)",
            "Beige: Bej (bej)",
            "Black: Siyah (blek)",
            "Bee: Arı (bii)",
            "Bald Eagle: Kel Kartal (bold igıl)",
            "Bear: Ayı (biyır)",
            "Bat: Yarasa (beet)",
            "Badger: Porsuk (becır)",
            "Brother: Erkek kardeş (bradır)",
            "Bike: Bisiklet (bayk)",
            "Budgie: Muhabbet Kuşu (baci)",
            "Beginner: Acemi (beginır)",
            "Below: Altında (bılov)",
            "Before: Önce (bifor)",
            "Beautiful: Güzel (bitiful)",
            "Bag: Çanta (beg)",
            "Broken: Kırık (brokın)",
            "Beef: Dana eti (biif)",
            "Bread: Ekmek (bred)",
            "Borrow: Ödünç almak (barrov)",
            "Believe: İnanmak (bıliv)",
            "Begin: Başlamak (begin)",
            "Brand: Marka (brend)",
            "Bachelor: Lisans, bekar (beşılır)",
            "Beard: Sakal (biyırd)",
            "Birthday: Doğum günü (börtdey)",
            "Be lost: Kaybolmak (bi last)",
            "Be patient: Sabretmek (bi peyşın)",
            "Bet: İddiaya girmek (bet)",
            "Butter: Tereyağı (badır)",
            "Basin: Havza (beysın)",
            "Bay: Defne, koy, körfez (bey)",
            "Beach: Plaj (biiç)",
            "Better: Daha iyi (bedır)",
            "By accident: Kazayla (bay eksidınt)",
            "By mistake: Yanlışlıkla (bay misteyk)",
            "By choice: Tercihen (bay çoys)",
            "By no means: Hiçbir şekilde (bay no miins)",
            "By all means: Her türlü (bay oll miins)",
            "By chance: Tesadüfen (bay çeyns)",
            "By force: Zorla (bay fors)",
            "Boss: Patron (bass)",
            "Blow: Darbe (blov)",
            "Best: En iyi (best)",
            "Bite: Isırmak (bayt)",
            "Bring: Getirmek (bring)",
            "Bright: Parlak (brayt)",
            "Bosom buddy: Yakın arkadaş, kanka",
            "Bargain: Pazarlık yapmak",
            "Bother: Dert",
            "Basic: Temel, ana",
            "Boost: Artırmak",
            "Butter: Tereyağı",
            "Budget: Bütçe",
            "Break: Kırmak",
            "Bridge: Köprü",
            "Brush: Fırçalamak",
            "Boring: Sıkıcı",
            "Brave: Cesur",
            "Break up: (Birinden) Ayrılmak",
            "Blunder: Çok kötü hata, büyük hata",
            "Beg: Yalvarmak",
            "Be: Olmak",
            "Bringe: Getirmek",
            "Behaviour: Davranış",
            "Bury: Gömmek",
            "Bad: Kötü",
            "Bathroom: Banyo",
            "Building: Bina",
            "Bacon: Domuz pastırması",
            "Bullet: Kurşun",
            "Bumpy: Engebeli",
            "Breath: Soluk, nefes",
            "Borrow: Ödünç almak",
            "Briefly: Kısaca",
            "Backyard: Arkabahçe (Amerika)",
            "Bedroom: Yatak odası",
            "Basement: Bodrum kat",
            "Balcony: Balkon",
            "Bed: Yatak",
            "Bedside table: Komodin",
            "Blanket: Battaniye",
            "Bookcase: Kitaplık",
            "Bookshelf: Kitap rafı (Kitaplık olarak da kullanılır)",
            "Bounty: Ödül",
            "Betray: İhanet etmek",
            "Brake: Fren",
            "Broom: Süpürge",
            "Blond: Sarışın (Erkekler için)",
            "Blonde: Sarışın (Kadınlar için)",
            "C / c",
            "Cook: Aşçı",
            "Cake: Kek",
            "Chemist: Eczacı",
            "Captain: Kaptan",
            "Cashier: Kasiyer",
            "Cat: Kedi",
            "Cow: İnek",
            "Crab: Yengeç",
            "Chicken: Tavuk",
            "Crow: Karga",
            "Camel: Deve",
            "Crocodile: Timsah",
            "Cousin: Kuzen",
            "Connection: Bağlantı",
            "Collection: Koleksiyon",
            "Cut: Kesmek",
            "Choose: Seçmek, tercih etmek",
            "Correct: Doğru",
            "Complete: Tamamlamak",
            "Colour: Renk",
            "Clean: Temizlemek",
            "Clue: İpucu",
            "Coward: Korkak",
            "Component: Bileşen",
            "Cell: Hücre",
            "Cite: Bahsetmek",
            "Competition: Yarışma, rekabet",
            "Concert: Konser",
            "Concerted: Uyumlu",
            "Conversely: Aksine",
            "Coincide: Rastlamak",
            "Convey: İletmek",
            "Capital: Başkent",
            "Cup: Fincan",
            "Chess: Satranç",
            "Currently: Şu anda",
            "Come out: Ortaya çıkmak",
            "Conversation: Konuşmak, görüşme, sohbet",
            "Christmas Day: Noel Günü",
            "Century: Yüzyıl",
            "Clothe: Kıyafet",
            "Coat: Ceket",
            "Convey: İletmek",
            "Calender: Takvim",
            "Composed: Sakin",
            "Coin: Madeni para",
            "Circumstance: Durum, koşul",
            "Choise: Seçim",
            "Circle: Daire, halka",
            "Capable: Yetenekli",
            "Corner: Köşe",
            "Cad: Aşağılık, ahlaksız kimse",
            "Canned: Konserve",
            "Careless: Dikkatsiz",
            "Chair: Sandalye",
            "Channel: Kanal",
            "Coast: Sahil",
            "Cave: Mağara",
            "Canyon: Kanyon",
            "Cliff: Uçurum",
            "Carry on: Sürdürmek",
            "Component: Bileşen",
            "Curse: Lanet",
            "Criminal: Adli",
            "Crime: Suç",
            "Count: Saymak",
            "Candy: Şeker",
            "Complete: Tamamlayınız",
            "Condemn: Kınamak",
            "Citizen: Vatandaş",
            "City: Şehir",
            "Cell: Hücre",
            "Cite: Bahsetmek",
            "Comparing: Kıyaslama",
            "Conversation: Sohbet",
            "Choke: Boğulmak",
            "Cold: Soğuk",
            "Copper: Bakır",
            "Cup: Fincan",
            "Ceiling: Tavan (siyılin)",
            "Celebrate: Kutlamak (selıbreyt)",
            "Convince: İkna etmek",
            "Coast: Deniz kıyısı",
            "Climb: Tırmanmak",
            "Certain: Kesin",
            "Copter: Helikopter",
            "Carpenter: Marangoz (karpıntır)",
            "Compassion: Şefkat (kımpeşın)",
            "Command: Komut",
            "Cable: Kablo",
            "Courage: Cesaret",
            "Cost: Masraf",
            "Carnival: Karnaval",
            "Calm: Sakin",
            "Calm down: Sakin ol",
            "Cheap: Ucuz",
            "Cunning: Kurnaz",
            "Comb: Tarak",
            "Confess: İtiraf etmek",
            "Clean: Temiz",
            "Clumsy: Beceriksiz",
            "Clasp: Toka",
            "Comfortable: Rahat",
            "Chapter: Bölüm",
            "Common: Yaygın",
            "Concrete: Beton",
            "Conduct: Yönetmek",
            "Culture: Kültür",
            "Cheerful: Neşeli",
            "Case: Dava",
            "Citizen: Vatandaş",
            "Chew: Çiğnemek",
            "Compare: Karşılaştırma",
            "Corridor: Koridor",
            "Celler: Kiler",
            "Couch: İkili kanepe",
            "Coffee table: Sehpa",
            "Chair: Sandalye",
            "Carpet: Halı",
            "Curtain: Perde",
            "Chest of drawers: Çekmeceli dolap",
            "Closet: Gömme dolap tarzında",
            "Cushion: Yastık",
            "Cooker: Ocak",
            "Cure: Tedavi etmek",
            "Confirm: Onaylamak, doğrulamak",
            "Crook: Dolandırıcı, sahtekâr",
            "Convenience: Kolaylık, uygunluk, uygun zaman",
            "Credible: Güvenilir",
            "Collaboration: İşbirliği",
            "Careful: Dikkatli",
            "Customer: Müşteri",
            "Contain: İçermek",
            "Crowd: Kalabalık",
            "Collision: Çarpışma",
            "Curious: Meraklı",
            "Consummate: Mükemmel",
            "Charisma: Karizma / Karizmatik",
            "Chalk: Tebeşir",
            "Clever: Zeki",
            "D / d",
            "Doctor: Doktor",
            "Dancer: Dansöz, dansçı",
            "Dentist: Dişçi",
            "Driver: Şoför",
            "Diver: Dalgıç (dayvır)",
            "Dog: Köpek",
            "Duck: Ördek",
            "Dove: Güvercin",
            "Deer: Geyik",
            "Dolphin: Yunus",
            "Daughter: Kız evlat",
            "Deep: Derin",
            "Dreaming: Hayal",
            "Desk: Masa",
            "Difficult: Zor",
            "Done: Bitti",
            "Divorce: Boşanma, boşanmış",
            "Deserve: Hak etmek",
            "Disapper: Kaybolmak",
            "Dream: Rüya",
            "Diction: Diksiyon",
            "Desert: Çöl",
            "Darkness: Karanlık",
            "Dislike: Beğenmemek",
            "Dormitory: Yurt",
            "Destroy: Yok etmek",
            "Detail: Detay",
            "Demand: Talep etmek",
            "Dress: Elbise",
            "Drag: Sürüklemek",
            "Deactive: Etkisiz hâle getirmek",
            "Daily: Günlük",
            "Deadline: Son teslim tarihi",
            "Dept: Borç",
            "Dune: Kumdan tepe",
            "Delta: Delta",
            "Danger: Tehlike",
            "Dangerous: Tehlikeli",
            "Delight: Lokum",
            "Delicate: Narin",
            "Desperate: Umutsuz",
            "Deny: Reddetmek",
            "Dry: Kuru",
            "Delicious: Lezzetli (dılışıs)",
            "Disturb: Rahatsız etmek (distörb)",
            "Definitely: Kesinlikle",
            "Distance: Mesafe",
            "Drive: Sürmek",
            "Decay: Çürümek",
            "Drop: Düşürmek",
            "Describe: Tanımlamak",
            "Destination: Hedef",
            "Divide: Bölmek",
            "Die: Ölmek ",
            "Dead: Ölü",
            "Determined: Kararlı",
            "Deliver: Teslim etmek",
            "Driving Licence: Ehliyet",
            "Decision: Karar",
            "Dictionary: Sözlük",
            "Desire: Arzu etmek",
            "Decide: Karar vermek",
            "Determine: Belirlemek",
            "Data: Veri",
            "Database: Veri tabanı",
            "Data breach: Veri ihlali",
            "Drowsiness: Uykulu olmak, uyuşukluk",
            "Deal: Anlaşma",
            "Durability: Dayanıklılık",
            "Dogged: İnatçı",
            "Division: Bölme işlemi",
            "Door: Kapı",
            "Dining table: Yemek masası",
            "Decorative lamps: Lambader (Ayaklı lamba)",
            "Double bed: Çift kişilik yatak",
            "Dressing Table: Makyaj masası",
            "Deep freezer: Derin dondurucu",
            "Dishwasher: Bulaşık makinası",
            "Desk: Çalışma masası",
            "Drawer: Çekmece",
            "Diversity: Çeşitlilik",
            "Democracy: Demokrasi",
            "Dismiss: Kovmak",
            "Design: Tasarım / Tasarlamak",
            "Drizzle: Çiseleyen yağmur",
            "Dive: Dalış / Dalmak",
            "Delirium: Sayıklama",
            "Defend: Savunmak",
            "Donate: Bağış",
            "Discuss: Tartışmak",
            "E / e",
            "Engineer: Mühendis",
            "Elecrician: Elektrikçi",
            "Elephant: Fil",
            "Expensive: Pahalı",
            "Enough: Yeterli",
            "Enjoyable: Zevkli",
            "Exam: Sınav",
            "Engage: Söz vermek",
            "Explore: Keşfetmek",
            "Each: Her biri",
            "Emergency notice: Acil durum uyarısı",
            "Effort: Çaba, çaba göstermek",
            "Experience: Deneyim kazanmak",
            "Examine: İncelemek, muayene etmek",
            "Exist: Var olmak",
            "Existence: Varoluş",
            "Event: Etkinlik / Olay",
            "Eagle: Kartal",
            "Ethereal: Ruhani",
            "Easter: Paskalya",
            "Expatriate: Gurbetçi",
            "Exactly: Kesinlikle",
            "Early: Erken ",
            "Elbow: Dirsek",
            "Eyebrow: Kaş",
            "Emotion: Duygu",
            "Each: Her biri",
            "European Union: Avrupa Birliği",
            "Expert: Uzman",
            "Error: Hata",
            "Edition: Baskı, yayın",
            "Epidemic: Salgın",
            "Ear: Kulak",
            "Expect: Dışında, hariç",
            "Engine: Motor, makine",
            "Employer: İşveren",
            "Excited: Heyecanlı",
            "Explain: Açıklamak",
            "Elevator: Asansör",
            "Erode: Aşındırmak, yıpranmak",
            "Experience: Deneyim",
            "Entrance: Giriş",
            "Exit: Çıkış",
            "Earn: Kazanmak",
            "Earth: Dünya",
            "Earthquake: Deprem",
            "Evacuate: Tahliye etmek, boşaltmak",
            "Equality: Eşitlik",
            "Exploit: Kendi çıkarı için kullanmak, sömürmek",
            "Eager: İstekli, hevesli",
            "Esteem: Saygı, itibar",
            "Explode: Patlamak",
            "Enevtually: Sonunda",
            "Effortless: Çok kolay / Zahmetsiz",
            "Evolution: Evrim",
            "F / f",
            "Freelancer: Serbest çalışan",
            "Fisherman: Balıkçı",
            "Florist: Çiçekçi",
            "Farmer: Çiftçi",
            "Fireman: İtfaiyeci",
            "Fish: Balık",
            "Fox: Tilki",
            "Frog: Kurbağa",
            "Family: Aile",
            "Father: Baba",
            "Floor: Kat",
            "Far from: Çok uzakta",
            "Favourite: Favori",
            "Florist: Çiçekçi",
            "Friend: Arkadaş",
            "Family: Aile",
            "Fix: Düzeltmek, saptamak",
            "Fragile: Kırılgan, hassas",
            "Founder: Kurucu",
            "Frustration: Hayal kırıklığı",
            "Flame: Alev",
            "Famous: Tanınmış, ünlü",
            "Fire: Yangın",
            "Formal: Resmi",
            "Future: Gelecek",
            "Finger: Parmak",
            "Forest: Orman",
            "Fascinating: Büyüleyici",
            "Functional: İşlevsel",
            "File: Dosya",
            "Felt like: Gibi hissettim",
            "Fume: Duman",
            "Fact: Gerçek",
            "Finite: Sınırlı",
            "Field: Alan, tarla",
            "Forecast: Tahmin",
            "Forgive: Bağışlamak",
            "Fascinating: Büyüleyici",
            "Freedom: Özgürlük",
            "Fragile: Kırılgan (frecıl)",
            "Fluent: Akıcı, sürükleyici (fluvınt)",
            "Fussy: Mızmız",
            "Forbidden: Yasak",
            "Familiar: Aşina",
            "Ferry: Vapur",
            "Fall: Düşmek",
            "Fly: Uçmak",
            "Fearful: Ürkek",
            "Fold: Katlamak",
            "Find: Bulmak",
            "Feature: Özellik",
            "Farm: Çiftlik",
            "Flour: Un",
            "Fraud: Dolandırıcı",
            "Fill: Doldurmak",
            "Fair: Adil",
            "Flat: Düz",
            "Founder: Kurucu",
            "Farewell: Elveda",
            "Feather: Tüy",
            "Front yard: Ön bahçe (İngiltere)",
            "Floor: Yer",
            "Fridge: Buzdolabı",
            "Fidelity: Vefa",
            "Flag: Bayrak",
            "Fun: Eğlenceli",
            "Flow: Akmak, akış",
            "Female: Kadın",
            "Fascinating: Çok ilginç",
            "Faithful: Sadık",
            "Fork: Çatal",
            "Fake: Sahte",
            "G / g",
            "Grocer: Bakkal",
            "Graphic designer: Grafiker",
            "Grey / Gray: Gri",
            "Green: Yeşil",
            "Gold: Altın",
            "Goldfish: Süs balığı",
            "Goat: Keçi",
            "Giraffe: Zürafa",
            "Gorilla: Goril",
            "Grandfather: Büyükbaba",
            "Grandmother: Büyükanne",
            "Glass: Bardak",
            "Garden: Bahçe (America)",
            "Greengrocer: Manav",
            "Gift: Hediye",
            "Gap: Boşluk",
            "Go Down: Batmak",
            "Grow: Yetişmek, büyümek",
            "Glacier: Buzul",
            "Geyser: Gayzer",
            "Gulf: Körfez",
            "Grand: Büyük",
            "Gravity: Yerçekimi",
            "Gentleman: Beyefendi (centılmen)",
            "Guide: Rehber",
            "Glazier: Camcı",
            "Garage: Garaj",
            "Greet: Selamlamak",
            "Get: Almak",
            "General: Genel",
            "Government: Hükümet, devlet",
            "Good: İyi",
            "Gate: Bahçe kapısı",
            "Guestroom: Misafir odası",
            "Gas: Benzin",
            "Guess: Tahmin",
            "Giant: Kocaman / Dev",
            "Graceful: Zarif",
            "Generally: Genellikle",
            "H / h",
            "House painter: Boyacı",
            "Housewife: Ev hanımı",
            "Hairdresser: Kuaför",
            "Horse: At",
            "Hawk: Şahin",
            "Hedgehog: Kirpi",
            "Hare: Yabani tavşan",
            "Husband: Eş (Erkek)",
            "Headphone: Kulaklık",
            "Hair: Saç",
            "Holiday: Tatil",
            "Health: Sağlık",
            "Healthy: Sağlıklı",
            "Hell: Cehennem",
            "Hide: Saklanmak",
            "Humidity: Nem",
            "Hurry: Acele",
            "Happy: Mutlu",
            "Happiness: Mutluluk",
            "Honor: Onur",
            "Honorable: Onurlu",
            "Human: İnsan",
            "Humanity: İnsanlık",
            "Hope: Umut etmek",
            "Hate: Nefret etmek",
            "Homework: Ev ödevi",
            "Hat: Şapka",
            "Hanger: Askı",
            "Hill: Tepe",
            "How: Nasıl",
            "How far: Ne kadar",
            "How often: Ne sıklıkta",
            "Honest: Dürüst",
            "Horizon: Ufuk",
            "Hardly: Güçlükle",
            "Heartache: Gönül yarası",
            "Hold: Tutmak, tutunmak",
            "Happen: Olmak (Nothing will happen today: Bugün bir şey olmayacak)",
            "Hire: Kiralamak",
            "Hurt: Acıtmak, incitmek",
            "Hardwork: Sıkı çalışma",
            "Humor: Espri / Mizah",
            "Heart: Kalp",
            "High: Yüksek",
            "Hiccup: Hıçkırık",
            "Horizontal: Yatay",
            "Helpful: Yardımsever",
            "Hammock: Hamak",
            "However: Ancak",
            "Height: Yükseklik",
            "Hallway: Koridor",
            "Hall: Salon",
            "Homeland: Vatan",
            "Hazardous: Tehlikeli",
            "Hour: Saat",
            "Hear: Duymak",
            "Horrible: Korkunç",
            "Hush: Sessizlik / Susmak",
            "Heaven: Cennet",
            "I / i",
            "Individual: Bireysel",
            "Intelligent: Zeki",
            "Island: Ada",
            "Import: İthal etmek",
            "Impact: Etki",
            "Ice cream: Dondurma",
            "Input: Giriş",
            "Instruction: Talimat",
            "Invalid: Geçersiz",
            "Independence: Bağımsızlık",
            "Install: Kurmak, yüklemek",
            "Iceberg: Buzdağı",
            "Issue: Konu",
            "Issues: Sorunlar",
            "In case: İhtimale karşı, durumunda",
            "Insist: Israr etmek",
            "Interrupt: Kesmek, bölmek",
            "In the wake of: Ardından (in dı veyk of)",
            "Improvise: Uydurmak (impruvays)",
            "Instead: Yerine, bunun yerine (insteed)",
            "Impute: Suçlamak, itham etmek",
            "Inform: Bilgilendirmek",
            "Invent: İcat etmek",
            "Insect: Böcek",
            "Imply: Kastetmek, ima etmek",
            "Inspector: Müfettiş",
            "Influence: Etki, etkilemek",
            "Investment: Yatırım",
            "Invite: Davet etmek",
            "Invicible: Yenilmez",
            "Ignore: Önemsememek",
            "Inevitable: Kaçınılmaz",
            "Insect: Böcek",
            "Increase: Artırmak",
            "Imitation: Taklit",
            "Indefinite: Belirsiz",
            "Include: Dahil etmek",
            "Insure: Sigortalamak",
            "Improve: Gelişmek",
            "Impatient: Sabırsız",
            "Ignorance: Cahillik",
            "Isolate: Yalnız bırakmak, izole etmek",
            "Intuitively: Sezgisel, sezgiye dayalı",
            "Impress: Etkilemek",
            "Icy: Buzlu",
            "Insert: Eklemek",
            "Installment: Taksit",
            "International: Uluslararası",
            "Iron: Ütü",
            "Infinite: Sonsuz",
            "Infinity: Sonsuzluk",
            "Interesting: İlginç",
            "J / j",
            "Journalist: Gazeteci",
            "Judge: Hâkim",
            "Jacket: Ceket",
            "Job: Meslek",
            "Juice: Meyve suyu",
            "Jungle: Orman",
            "Joke: Şaka",
            "Jeweller: Kuyumcu (civılır)",
            "Joy: Sevinç, neşe",
            "Journey: Yolculuk",
            "Juicy: Sulu",
            "Join: Katılmak",
            "Jealous: Kıskanç",
            "Justice: Adalet",
            "K / k",
            "Kitten: Yavru kedi",
            "Kangaroo: Kanguru",
            "Key: Anahtar",
            "Kiss: Öpmek",
            "King: Kral",
            "Kingdom: Krallık",
            "Keep: Tutmak",
            "Knowledge: Bilgi",
            "Knight: Şövalye",
            "Knee: Diz",
            "Knife: Bıçak",
            "Knock down: Yere sermek",
            "Kitchen: Mutfak",
            "Kettle: Ketıl",
            "L / l",
            "Lawyer: Avukat",
            "Locksmith: Çilingir",
            "Librarian: Kütüphaneci",
            "Lilac: Lila",
            "Lion: Aslan",
            "Lizard: Kertenkele",
            "Look: Bakmak",
            "Live: Canlı, yaşamak, yaşayan",
            "Lung: Akciğer",
            "Legacy: Miras",
            "Letter: Mektup",
            "Listen: Dinlemek",
            "Luck: Şans",
            "Learn: Öğrenmek",
            "Lost: Kayıp",
            "Lunch: Öğle yemeği",
            "Laughter: Kahkaha",
            "Liberty: Özgürlük",
            "Literature: Edebiyat",
            "Lie: Yalan",
            "Lead: Yol göstermek",
            "Likely: Muhtemel",
            "Lease: Kiralama",
            "Lick: Yalamak",
            "Lighter: Çakmak",
            "Ladder: Merdiven",
            "Loud: Gürültü",
            "Loose: Bol",
            "Lack: Eksiklik (leek)",
            "Loyalty: Sadakat",
            "Lenght: Uzunluk",
            "Label: Etiket",
            "Lambkin: Kuzucuk",
            "Late: Geç",
            "Lack: Eksiklik",
            "Labor: Çalışmak, uğraşmak",
            "Line: Satır, çizgi",
            "Little: Küçük, az",
            "Lie: Yalan",
            "Liar: Yalancı",
            "Love: Sevmek",
            "Lay: Sermek",
            "Lagguage: Valiz, bagaj",
            "Letter: Mektup",
            "Lusty: Kuvvetli",
            "Livingroom: Oturma odası",
            "Lawbreaker: Kural tanımaz",
            "Lag: Gecikme",
            "Leg: Bacak",
            "Lazy: Tembel",
            "Lettuce: Marul",
            "Leaf: Yaprak",
            "Leather: Deri",
            "M / m",
            "Musician: Müzisyen",
            "Mechanic: Tamirci",
            "Mouse: Fare",
            "Monkey: Maymun",
            "Mole: Köstebek",
            "Mother: Anne",
            "Met: Tanışmak",
            "Meet: Buluşmak",
            "Money: Para (maniy)",
            "Monkey: Maymun",
            "Magnificent: Muhteşem",
            "Medicine: İlaç",
            "Married: Evli",
            "Might: Olabilir",
            "Multiplation: Çoğalma",
            "Meat: Et",
            "Morning: Gündüz",
            "Move: Hareket",
            "Move to: Taşınmak",
            "Miracle: Mucize",
            "Mirage: Serap",
            "Math: Matematik",
            "Match: Maç, eşleşme",
            "Mutual Friend: Ortak arkadaş",
            "Matchless: Eşsiz, rakipsiz",
            "Midnight: Gece yarısı ",
            "Mushroom: Mantar",
            "Manage: Yönetmek",
            "Mobilization: Seferberlik",
            "Mercy: Acımak",
            "Master: Usta",
            "Majority: Çoğunluk",
            "Meal: Öğün",
            "Mountain: Dağ",
            "Mesa: Yüksek ova",
            "Mystery: Gizem",
            "Mess: Dağınıklık",
            "Mirror: Ayna",
            "Moment: An",
            "Mushroom: Mantar",
            "Melt: Erimek",
            "Mend: Onarmak",
            "Mad: Çok sinirli",
            "Maintain: Sürdürmek",
            "Multiplication table: Çarpım tablosu",
            "Make: Yapmak",
            "Muscle: Kas",
            "Melt: Erimek",
            "Motherhood: Annelik",
            "Mind: Zihin",
            "Mirror: Ayna",
            "Mattress: Şilte (Nevresim)",
            "Mist: Sis",
            "Marriage: Evlilik",
            "Misfortune: Şanssızlık",
            "Male: Erkek",
            "Matter: Önemli",
            "Mouth: Ağız",
            "Massacre: Katliam",
            "Mission: Görev",
            "Mostly: Çoğunlukla",
            "N / n",
            "Nurse: Hemşire",
            "Navy blue: Lacivert",
            "Nephew: Erkek yeğen",
            "Niece: Kız yeğen",
            "Now: Şimdi",
            "Night: Gece",
            "Noun: İsim",
            "Neighbour: Komşu",
            "Noon: Öğle vakti",
            "Neglect: İhmal",
            "Notice: Fark etmek",
            "Never mind: Boş ver",
            "Notification: Bildirim",
            "Niggard: Cimri kimse",
            "Need: İhtiyaç",
            "Needy: Muhtaç",
            "Nervous: Sinirli",
            "Never: Asla",
            "Now and now: Defalarca (nav en nav)",
            "Nail: Tırnak",
            "Nation: Ulus, millet",
            "National: Ulusal",
            "Necessity: Gereklilik",
            "Nauseate: İğrenmek",
            "Narrow: Dar",
            "Negotiation: Müzakere",
            "Needless: Gereksiz, lüzumsuz",
            "Nutrient: Besin, gıda",
            "Nevertheless: Yine de / olmasına rağmen",
            "Nowhere: Hiçbir yer",
            "Novel: Roman",
            "Noisy: Gürültülü",
            "O / o",
            "Orange: Turuncu",
            "Ostrich: Devekuşu",
            "Owl: Baykuş",
            "Ox: Öküz",
            "Otter: Su samuru",
            "Owner: Sahip",
            "Occupation: Meslek",
            "Oil: Yağ",
            "Objective: Amaç",
            "Object: Nesne",
            "Outside: Dışarda",
            "Officer: Memur",
            "Odd: Tuhaf",
            "Oasis: Vaha",
            "Ocean: Okyanus",
            "Own: Sahip olmak",
            "Over: Üzerinde",
            "Order: Sipariş",
            "Origin: Başlangıç",
            "Open minded: Açık görüşlü",
            "Obligation: Yükümlülük, zorunluluk",
            "Omit: Çıkarmak, dahil etmemek",
            "Oven: Fırın",
            "Obtain: Elde etmek, edinmek",
            "Official: Resmi",
            "Owe: Borçlu olmak",
            "Obvious: Apaçık",
            "Oven: Fırın",
            "Overcome: Üstesinden gelmek / Aşmak",
            "Onion: Soğan",
            "Other: Diğer",
            "Overclock: Hız aşırtma / Hız aşımı",
            "Opportunity: Fırsat",
            "P / p",
            "Priest: Papaz",
            "Photographer: Fotoğrafçı",
            "Pilot: Pilot",
            "Policeman: Polis (Erkek)",
            "Policewoman: Polis (Kadın)",
            "Politician: Politikacı",
            "Postman: Postacı",
            "Psychologist: Psikolog",
            "Plumber: Su tesisatçısı",
            "Pink: Pembe",
            "Purple: Mor",
            "Puppy: Yavru köpek",
            "Parrot: Papağan",
            "Pig: Domuz",
            "Pigeon: Güvercin",
            "Peacock: Tavuskuşu",
            "Panda: Panda",
            "Parents: Ebeveynler",
            "Plural: Çoğul",
            "Pet: Evcil hayvan",
            "Profession: Meslek",
            "Pharmacist: Eczacı",
            "Pleasure: Zevk",
            "Pain: Acı, ağrı",
            "Painful: Ağrılı",
            "Prefer: Tercih etmek",
            "Paradise: Cennet",
            "Phantom: Hayalet",
            "Pork: Domuz eti",
            "Pen: Dolma kalem",
            "Pending: Bekliyor",
            "Pencil: Kalem",
            "Product: Ürün",
            "Precip: Hızlı",
            "Preciptation: Yağışlı",
            "Precipice: Uçurum",
            "Pupil: Öğrenci",
            "Pharmacy: Eczane",
            "Park: Park",
            "Place: Yer",
            "Physics: Fizik",
            "Prepare: Hazırlamak",
            "Progress: İlerleme",
            "Pants: Pantolon",
            "Peak: Zirve",
            "Predict: Tahmin",
            "Perceive: Algılamak",
            "Preposition: Edat",
            "Pit: Çukur",
            "Paper: Kâğıt",
            "Polish: Parlatmak",
            "Plate: Tabak",
            "Prepare: Hazırlamak",
            "Plateau: Yayla",
            "Peninsula: Yarımada",
            "Plain: Sade / düz",
            "Prairie: Çayır",
            "Pay: Ödemek",
            "Pleasure: Zevk, keyif",
            "Pettish: Hırçın, huysuz",
            "Pepper: Biber",
            "Perhaps: Belki",
            "Perseverance: Azim",
            "Possible: Mümkün, olası",
            "Poetry: Şiir",
            "Punishment: Ceza",
            "Peace: Barış",
            "Poor: Yoksul",
            "Pour: Dökmek",
            "Proof: Kanıt",
            "Patient: Hasta",
            "Pot: Tencere",
            "Plant: Bitki",
            "Pair: Çift, iki parçadan oluşan şey (A pair of shoes)",
            "Practice: Uygulama",
            "Produce: Üretmek",
            "Permission: İzin",
            "Plus: Artı",
            "Provide: Sağlamak",
            "Port: Liman",
            "Permanent: Kalıcı (pörmınınt)",
            "Person: Kişi, insan",
            "Pedestrain: Yaya",
            "Patience: Sabır",
            "Prepare: Hazırlamak",
            "Penny bank: Kumbara",
            "Population: Nüfus",
            "Purpose: Amaç",
            "Primary: Birincil, ana",
            "Perhaps: Belki",
            "Proof: Kanıt",
            "Probably: Muhtemelen",
            "Prison: Hapishane",
            "Pretty: Sevimli",
            "Punish: Cezalandırmak",
            "Punisher: Cezalandırıcı",
            "Pipe: Boru",
            "Philosophy: Felsefe",
            "Put: Koymak",
            "Pronoun: Zamir",
            "Perfect: Mükemmel",
            "Pleasant: Hoş, keyifli",
            "Perspective: Bakış açısı",
            "Partnership: Ortaklık",
            "Promise: Söz vermek",
            "Preserve: Korumak",
            "Pullovers: Kazak",
            "Principle: Prensip",
            "Pool: Havuz",
            "Painting: Tablo",
            "Picture: Resim",
            "Pillow: Yastık",
            "Pillowcase: Yastık kılıf",
            "Poster: Poster",
            "Plug: Fiş",
            "Praise: Övgü",
            "Public: Halk",
            "Privacy: Gizlilik",
            "Plane: Uçak",
            "Pendulum: Sarkaç",
            "Prove: Kanıtlamak",
            "Pull: Çekmek",
            "Profit: Kâr",
            "Path: Yol / Patika",
            "Proud: Gururlu",
            "Property: Mülk",
            "Passenger: Yolcu",
            "Q / q",
            "Question: Soru",
            "Quickly: Hızlı bir şekilde, hızlı",
            "Quandary: Kararsızlık",
            "Quite: Epeyce",
            "Queen: Kraliçe",
            "Query: Sorgu",
            "Quality: Kalite",
            "Quilt: Yorgan",
            "Quince: Ayva",
            "R / r",
            "Reporter: Muhabir",
            "Red: Kırmızı",
            "Rabbit: Tavşan",
            "Raccoon: Rakun",
            "Rat: Sıçan",
            "Right: Haklı",
            "Rest: Dinlenmek",
            "Rent: Kira, kiralamak",
            "Receive: Teslim alma",
            "Rain: Yağmur",
            "Run: Koşmak",
            "Result: Sonuç",
            "Reply: Cevap",
            "Rain: Yağmur",
            "Remote: Uzak",
            "Reaction: Tepki",
            "Regret: Pişmanlık, pişman olmak",
            "Restaurant: Restoran",
            "Rigorous: Titiz",
            "Reach: Ulaşmak",
            "Reasonable: Mantıklı",
            "River: Nehir",
            "Rain forest: Yağmur ormanı",
            "Reach: Ulaşmak",
            "Rotate: Döndürmek",
            "Rescue: Kurtarmak",
            "Response: Yanıt",
            "Revere: Saymak, Saygı göstermek",
            "Requir: Gerek",
            "Required: Gereklidir",
            "Ringtone: Zil sesi",
            "Remote: Uzak",
            "Rusty: Paslı",
            "Recently: Son zamanlarda",
            "Remember: Hatırlamak (rimembır)",
            "Raise: Yükseltmek",
            "Refugee: Mülteci",
            "Responsible: Sorumlu, mesul",
            "Rank: Sıra",
            "Region: Bölge",
            "Root: Kök",
            "Rope: İp",
            "Round: Yuvarlak",
            "Recommend: Tavsiye etmek",
            "Round trip: Gidiş – dönüş (Bilet ile alakalıdır).",
            "Requirement: Gereklilik, ihtiyaç",
            "Regard: Saygı, saygınlık",
            "Republic: Cumhuriyet",
            "Right away: Derhal",
            "Reply: Cevap vermek",
            "Roof: Çatı",
            "Resent: Gücenmek",
            "Room: Oda",
            "Roof: Çatı",
            "Recover: İyileşmek",
            "Resing: İstifa etmek",
            "Riot: İsyan, ayaklanma, başkaldırma",
            "Rebel: İsyancı",
            "Rigid: Sert, katı",
            "Rhyme: Kafiye",
            "Rice: Omuz",
            "Relation: İlişki",
            "Retire: Emekli olmak",
            "Reflection: Yansıma",
            "Reflex: Refleks",
            "Revoke: İptal etmek",
            "Respect: Saygı",
            "Research: Araştırma",
            "Rose: Gül",
            "S / s",
            "Student: Öğrenci",
            "Soldier: Asker",
            "Scientist: Bilim adamı",
            "Surgeon: Cerrah",
            "Shepherd: Çoban",
            "Sailor: Denizci",
            "Singer: Şarkıcı",
            "Silver: Gümüş",
            "Shrimp: Karides",
            "Sheep: Koyun",
            "Sparrow: Serçe",
            "Seagull: Martı",
            "Swan: Kuğu",
            "Starfish: Denizyıldızı",
            "Snake: Yılan",
            "Son: Erkek evlat",
            "Sister: Kız kardeş",
            "Shoe(s): Ayakkabı - Ayakkabılar ",
            "Shower: Duş",
            "Strict: Sıkı, Sert",
            "Singer: Şarkıcı",
            "Stamp: Damga, pul",
            "Skyscraper: Gökdelen",
            "Scenery: Manzara",
            "Sentence: Cümle",
            "Sell: Satmak",
            "Space: Uzay, boşluk",
            "Stay: Beklemek, kalmak",
            "Swamp: Bataklık",
            "Ship: Gemi",
            "Salt: Tuz",
            "Sleep: Uyku",
            "Sleepy: Uykulu",
            "Sea: Deniz",
            "Search: Arama",
            "Seal: Mühür",
            "Sweetie: Tatlım, sevgili",
            "Sweat: Terlemek",
            "Suggest: Önermek",
            "Steam: Buhar",
            "Sign: İmzalamak",
            "Sincere: Samimi",
            "Shy: Çekingen",
            "Specialize: Uzmanlaşmak",
            "Select: Seçmek",
            "Sense: Duyu",
            "Satisfy: Tatmin etmek",
            "Sail: Yelken",
            "Snowy: Karlı, kar yağışlı",
            "Snow: Kar",
            "Shop: Dükkan",
            "Shopping: Alışveriş yapmak",
            "Sunset: Gün batımı",
            "Sunrise: Gün doğumu",
            "Suit: Takım elbise",
            "Shirt: Gömlek",
            "Skirt: Etek",
            "Sew up: Dikmek",
            "Stop: Durmak",
            "Stamp: Kâse",
            "See: Görmek",
            "Sea: Deniz",
            "Swim: Yüzmek",
            "Still: Hâlâ, yine de",
            "Sack: Çuval",
            "Salt: Tuz",
            "Scream: Çığlık",
            "Support: Desteklemek",
            "Swing: Salıncak",
            "Sandstorm: Kum fırtınası",
            "Skill: Beceri",
            "Suitcase: Bavul",
            "Sturdy: Sağlam",
            "Summit: Zirve",
            "Sibling: Kardeş",
            "Shame: Utanmak",
            "Street: Sokak",
            "Sacrifice Feast: Kurban Bayramı",
            "Sticky: Yapışkan",
            "Shield: Kalkan",
            "Sneakers: Spor ayakkabı",
            "Sensitive: Hassas",
            "Signboard: Tabela",
            "Strict: Katı",
            "Science: Bilim",
            "Science fact: Bilimsel gerçek",
            "Scientific: İlmî",
            "Story: Hikaye",
            "Sky: Gökyüzü",
            "Sword: Kılıç",
            "Swear: Yemin etmek ",
            "Shall we: Yapalım mı?",
            "Sink: Lavabo",
            "Special: Özel ",
            "Suddenly: Aniden",
            "Stage: Sahne, etap",
            "Silver: Gümüş",
            "Stream: Irmak",
            "Sweep: Süpürmek",
            "Stand: Ayakta durmak",
            "Stand up: Ayağa kalk",
            "Spend: Harcamak",
            "Shallow: Sığ",
            "Spark: Kıvılcım (spork)",
            "Secret: Gizli",
            "Stone: Taş",
            "Soul: Ruh",
            "Shout: Haykırmak",
            "Sincere: Samimi",
            "Sniff: Koklamak",
            "Slipper: Terlik",
            "Syllable: Hece",
            "Send: Göndermek",
            "Sentiment: Duyarlılık, hassaslık",
            "Survivor: Hayatta kalan",
            "Scales: Terazi",
            "Seperate: Ayrı",
            "Screen: Ekran",
            "Screenshot: Ekran görüntüsü",
            "Sweat: Ter",
            "Steel: Çelik",
            "Shameless: Utanmaz",
            "Study: Çalışmak",
            "Split up: (Birinden) Ayrılmak",
            "Sigh: İç çekmek, derin bir nefes almak",
            "Sow: Dikmek, ekmek",
            "Say: Söylemek",
            "Sort: Çeşit, tür",
            "Square: Kare",
            "Spill: Dökmek",
            "Success: Başarı",
            "Self-Improvement: Kişisel Gelişim",
            "Sharp: Keskin",
            "Silent: Sessiz",
            "Skinny: İnce, sıska",
            "Steep: Dik",
            "Supply: Tedarik etmek",
            "Suggest: Önermek",
            "Scope: Dürbün",
            "Shadow: Gölge",
            "Shampoo: Şampuan",
            "Shake: Sallamak",
            "Shake hands: El sıkışmak",
            "Shaken: Sarsılmış",
            "Schedule: Plan, program",
            "Solemn: Ciddi, ağırbaşlı",
            "Soft: Yumuşak",
            "Sofa: Kanepe",
            "Society: Toplum, dernek",
            "Skateboard: Kaykay",
            "Soil: Toprak",
            "Sincerity: Samimiyet",
            "Stick: Çubuk",
            "Swimming pool: Yüzme havuzu",
            "Sofa: Üçlü kanepe",
            "Single bed: Tek kişilik yatak",
            "Sofa bed: Çekyat",
            "Sheet: Çarşaf",
            "Shower cabin: Duşakabin",
            "Sink: Lavabo",
            "Shell: Kabuk",
            "Shine: Parlamak",
            "Sourcherry: Vişne",
            "Sneaky: Sinsi",
            "Size: Boyut",
            "Shoulder: Omuz",
            "Suppose: Varsaymak / Farz etmek",
            "Sip: Yudum",
            "Shave: Tıraş olmak",
            "Scout: İzci",
            "Salmon: Somon balığı",
            "Safe: Güvenli, Kasa",
            "T / t",
            "Teacher: Öğretmen",
            "Teach: Öğretmek",
            "Technician: Teknisyen",
            "Tailor: Terzi",
            "Turquoise: Turkuaz",
            "Turtle: Kaplumbağa",
            "Turkey: Hindi",
            "Tiger: Kaplan",
            "Taste: Damak zevki",
            "Twin: İkiz",
            "Thief: Hırsız",
            "Trust: Güven, güvenmek",
            "Treasure: Hazine",
            "Talent: Yetenek",
            "Tournament: Turnuva",
            "Tourney: Turnuva",
            "Try: Denemek",
            "Touch: Dokunma",
            "Torpid: Uyuşuk",
            "Torpedo: Torpido",
            "Terrible: Korkunç",
            "Therefore: Bu yüzden",
            "To Water: Sulamak",
            "Tundra: Tundra",
            "Tehmself: Kullanıcının kendisi",
            "Tell: Anlatmak, söylemek",
            "Translate: Çevirmek",
            "Transform: Dönüştürmek",
            "Tower: Kule",
            "Thanksgiving Day: Şükran Günü",
            "Title: Unvan",
            "Trade: Ticaret",
            "Together: Birlikte",
            "Taint: Leke",
            "Trick: Hile",
            "Tight: Sıkı",
            "Tear: Gözyaşı (teyr)",
            "Tactless: Patavatsız",
            "Tranquility: Huzur, sükûnet",
            "Tail: Kuyruk",
            "Throne: Taht",
            "Teeth: Diş",
            "Talent: Yetenek",
            "To avenge: İntikam almak",
            "To make a blunder: Pot kırmak",
            "Think: Düşünmek",
            "Triangle: Üçgen",
            "Tax: Vergi",
            "Town: Şehir",
            "Throw: Atmak",
            "Transfer: Aktarmak",
            "Truth: Gerçek",
            "TV (Television): Televizyon",
            "Tub: Küvet",
            "Tap: Musluk",
            "Towel: Havlu",
            "Toleration: Tolerans",
            "Tangerine: Mandalina",
            "Thick: Kalın",
            "Tiny: Çok küçük",
            "Talktive: Konuşkan",
            "Thrilling: Heyecan verici",
            "Teapot: Çaydanlık",
            "Therapy: Terapi / Tedavi",
            "U / u",
            "Unemployed: İşsiz",
            "Uncle: Amca/Dayı",
            "Upstairs: Üst katta",
            "Unfortunately: Maalesef, ne yazık ki",
            "Unreliable: Güvenilmez",
            "Ugly: Çirkin",
            "Umbrella: Şemsiye",
            "Use: Kullanmak",
            "Unfair: Haksız",
            "Unreal: Gerçek dışı",
            "Upset: Üzgün",
            "V / v",
            "Violet: Eflatun",
            "Verb: Fiil",
            "Voyage: Yolculuk",
            "Village: Köy",
            "Villager: Köylü",
            "Vase: Vazo",
            "Value: Değer",
            "View: Manzara",
            "Voluntarily: Gönüllü",
            "Visionary: Hayalperest",
            "Vowel: Sesli harf",
            "Various: Çeşitli",
            "Vocabulary: Kelime hazinesi, kelime bilgisi",
            "Visible: Görünür, açık",
            "Victory: Zafer",
            "Violin: Keman",
            "Violence: Şiddet, zorbalık",
            "Vaccine: Aşı",
            "Vital: Hayati",
            "W / w",
            "Waiter: Garson (Waitress: Kadın garsın)",
            "Worker: İşçi",
            "White: Beyaz",
            "Woodpecker: Ağaçkakan",
            "Walrus: Denizayısı",
            "Wife: Eş (Kadın)",
            "What: Ne",
            "Where: Nerede",
            "When: Ne zaman",
            "Why: Neden, niçin",
            "Who: Kim",
            "Whose: Kimin",
            "Which: Hangi",
            "Word: Kelime",
            "Wonder: Merak etmek",
            "Wrong: Yanlış",
            "Write: Yazmak",
            "Wise: Bilge",
            "Wed: Evlenmek",
            "Wedding: Düğün",
            "Wash: Yıkama",
            "Want: İstemek",
            "Weather: Hava",
            "Wear: Giymek, takmak",
            "Wine: Şarap",
            "Wild: Yabani",
            "Walk: Yürümek",
            "Waterfall: Şelale",
            "Wall: Duvar",
            "Wallpaper: Duvar kâğıdı",
            "War: Savaş",
            "Weather: Hava",
            "Weekday: Hafta içi",
            "While: -sırasında, -iken",
            "Whenever: Her ne zaman",
            "Worry: Endişe, endişelenmek",
            "Wet: Islak",
            "Watermelon: Karpuz",
            "Wood: Odun",
            "Waste: İsraf etmek",
            "Whale: Balina",
            "Wrist: Bilek",
            "Whole: Tüm",
            "Wardrope: Gardırop",
            "Wasching machine: Çamaşır makinası",
            "Wishper: Fısıldamak",
            "Witness: Tanık",
            "Wither: Solmak",
            "Wheat: Buğday",
            "X / x",
            "Xanthippe: Şirret kadın, Sokrat’ın karısı",
            "Xanthous: Sarı ırka ait",
            "Xeno: Yabancı",
            "Xenogamy: Çapraz tozlaşma (Çiçekler ile ilgili)",
            "Xenophobe: Yabancı düşmanı, yabancı sevmez",
            "Xenophobia: Ksenefobi, yabancı düşmanlığı, yabancı sevmezlik",
            "Xerox: Fotokopi, fotokopisini çekmek, kuru kopya",
            "Xeroxing: Fotokopisini çekmek",
            "Xmas: Noel",
            "Xylography: Tahta kalıptan resim basma",
            "Xylophone: Ksilofon (Çalgı türü)",
            "Xystus: Kapalı spor salonu",
            "Y / y",
            "Yellow: Sarı",
            "Yell: Bağırmak",
            "Yard: Avlu, bahçe (İngiltere)",
            "Z / z",
            "Zoo: Hayvanat bahçesi",
            "Zeal: Gayret, azim",
            "Zone: Bölge",
            "Zany: Delidolu"});
            this.listBox1.Location = new System.Drawing.Point(12, 64);
            this.listBox1.Name = "listBox1";
            this.listBox1.SelectionMode = System.Windows.Forms.SelectionMode.MultiSimple;
            this.listBox1.Size = new System.Drawing.Size(413, 264);
            this.listBox1.TabIndex = 0;
            // 
            // textBox1
            // 
            this.textBox1.Location = new System.Drawing.Point(141, 12);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new System.Drawing.Size(284, 34);
            this.textBox1.TabIndex = 1;
            this.textBox1.TextChanged += new System.EventHandler(this.textBox1_TextChanged);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(7, 15);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(128, 27);
            this.label1.TabIndex = 2;
            this.label1.Text = "Kelime Ara:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(7, 343);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(111, 27);
            this.label2.TabIndex = 5;
            this.label2.Text = "Kalıp Ara:";
            // 
            // textBox2
            // 
            this.textBox2.Location = new System.Drawing.Point(124, 340);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new System.Drawing.Size(284, 34);
            this.textBox2.TabIndex = 4;
            this.textBox2.TextChanged += new System.EventHandler(this.textBox2_TextChanged);
            // 
            // listBox2
            // 
            this.listBox2.FormattingEnabled = true;
            this.listBox2.ItemHeight = 26;
            this.listBox2.Items.AddRange(new object[] {
            "“Give me five!”: Çak bir beşlik!",
            "“Don’t make me laugh.”: Güldürme beni.",
            "“Don’t bother me.”: Beni rahatsız etme.",
            "“Don’t make me blush.”: Beni mahcup etme.",
            "“Whatever happen.”: Ne olursa olsun.",
            "“If you say so.”: Sen öyle diyorsan.",
            "“You owe me this.”: Bunu bana borçlusun.",
            "“What is with you?”: Senin derdin ne?",
            "“I can’t take it.”: Dayanamıyorum.",
            "“What do you want?”: Ne istiyorsun?",
            "“How old are you?”: Kaç yaşındasın?",
            "“Must i wait long?”: Çok bekleyecek miyim?",
            "“What do you do?”: Ne iş yapıyorsun?",
            "“That’s life.”: Hayat bu",
            "“What is the problem?”: Sorun nedir?",
            "“As you wish.”: Nasıl istersen",
            "“Around the World”: Dünya çapında",
            "“I am so tired...”: Öyle yorgunum ki...",
            "“Come back.”: Geri dön.",
            "“Stop bugging me!”: Beni rahat bırak!",
            "“Have a sit please.”: Otur lütfen.",
            "“I miss you badly.”: Seni çok özledim.",
            "“Me too.”: Ben de.",
            "“You too.”: Sen de.",
            "“Good luck.”: Bol şans.",
            "“Bless you!”: Çok yaşa!",
            "“Don’t rush me!”: İki ayağımı bir pabuca sokma!",
            "“Come to your senses!”: Aklını başına topla!",
            "“Shame on you!”: Sana yazıklar olsun!",
            "“Depends on you.”: Sana bağlı.",
            "“Don’t rab salt in my wound.”: Yarama tuz basma.",
            "“Are you kidding me?”: Benimle dalga mı geçiyorsun?",
            "“Mind your own business.”: Kendi işine bak.",
            "“In my opinion...”: Benim düşünceme göre…",
            "“Get out my life!”: Hayatımdan defol!",
            "“That’s all.”: Hepsi bu.",
            "“By the way...”: Bu arada...",
            "“Do me a favor.”: Bana bir iyilik yap.",
            "“Stay out of this!”: Sen karışma!",
            "“My gut tells me...”: İçimden bir ses diyor ki...",
            "“Time to time...”: Zaman zaman...",
            "“As for as I know.”: Bildiğim kadarıyla.",
            "“I am sorry to interrupt:” Böldüğüm için özür dilerim.",
            "“Where the tell have you been?”: Hangi cehennemdeydin?",
            "“For good.”: Temelli olarak.",
            "“You shouldn’t have.”: Zahmet etmeseydin.",
            "“To sum up”: Toparlayacak olursak.",
            "“Don’t make a scene!”: Rezillik çıkarma!",
            "“God give me patience!”: Allah’ım bana sabır ver!",
            "“What’s your rush?”: Ne bu acelen?",
            "“All I want is...”: Tek istediğim...",
            "“A shiver went up my spine!”: Ödüm koptu!",
            "“Never mind.”: Boş ver. (nevır maynd)",
            "“Forget about it.” Unut gitsin. (forget ebaut it)",
            "“Hurry up!” / “Get a move on!” / “Snap to it!”: Çabuk ol! (höri ap)",
            "“All of a sudden.”: Bir anda. (Al of e sadın)",
            "“Take it easy.”: Rahat ol. (teyk it iizi)",
            "“Calm down.”: Sakin ol. (kalm davn)",
            "“Watch out.”: Dikkatli ol. (voç avt)",
            "“What’s wrong?”: Sorun ne? (vats rong)",
            "“Why not?”: Neden olmasın (vay nat)",
            "“Cheer up!”: Neşelen! (çiır ap)",
            "“It doesn’t matter.”: Fark etmez. (it dazınt medır)",
            "“I’m lost.”: Kayboldum. (aym lost)",
            "“As I told you.”: Sana söylediğim gibi. (as ay told yu)",
            "“Don’t be Jealous!”: Kıskanma!",
            "“Keep in touch.”: İrtibatta kalalım.",
            "“Take care yourself.”: Sağlıcakla kal.",
            "“Under the weather.”: Keyfi kaçmış.",
            "“How does that sound?”: Ne dersin? (hav daz det savnd)",
            "“Just in case.”: Ne olur ne olmaz.",
            "“God forbid.”: Allah korusun.",
            "“In a nutshell...”: Kısaca, özet olarak...",
            "“What’s done is done.”: Olan oldu.",
            "“Not my cup of tea.”: Bana göre değil.",
            "“Behave yourself!”: Kendine gel!",
            "“Good Health to you.”: Sıhhatler olsun.",
            "“I can’t believe my eyes!”: Gözlerime inanamıyorum!",
            "“Use your head.”: Kafanı kullan.",
            "“Maybe some other time.”: Belki başka zaman.",
            "“I’m swamped.”: İşim başımdan aşkın.",
            "“Don’t be hypocrite!”: İkiyüzlü olma!",
            "“I’m breaking up with you.”: Senden ayrılıyorum.",
            "“That’s it.”: Bu kadar.",
            "“I didn’t mean it.”: Onu demek istemedim.",
            "“Figure it out!”: Bir yolunu bul!",
            "“According to me...”: Bana göre...",
            "“Not my concern!”: Beni ilgilendirmez!",
            "“Don’t let it get to you.”: Kafana takma.",
            "“What do you think?”: Ne düşünüyorsun?",
            "“Where do you get it?”: Nereden aldın?",
            "“What’s going on?”: Neler oluyor?",
            "“What do you want?”: Ne istiyorsun?",
            "“What are you doing?”: Ne yapıyorsun?",
            "“How do you feel?”: Nasıl hissediyorsun?",
            "“Not yet.”: Henüz değil.",
            "“I admire you!”: Sana hayranım!",
            "“Give me a hand.”: Bana el uzat (bana yardım et).",
            "“Believe me.”: İnan bana.",
            "“Call me back.”: Beni geri ara.",
            "“Consider it done!”: Oldu bil!",
            "“What’s the big deal?”: Bunda abartılacak ne var?",
            "“Tell me briefly what happened.”: Bana kısaca ne olduğunu anlat.",
            "“So glad I have you.”: İyi ki varsın.",
            "“I have goose bumps.”: Tüylerim diken diken oldu.",
            "“How much does it cost?”: Maliyeti nedir?",
            "“It doesn’t make sense.”: Bunun bir anlamı yok.",
            "“I’m very proud of you.”: Seninle gurur duyuyorum.",
            "“Let me see.”: İzin ver bir bakayım. / Dur bakayım.",
            "“Guess what.”: Bil bakalım ne oldu.",
            "“Don’t move!”: Kıpırdama!",
            "“Slow down!”: Yavaşla!",
            "“I decline.”: Reddediyorum.",
            "“Follow me.”: Beni takip et.",
            "“My treat.”: Ben ısmarlıyorum.",
            "“What would you recommend?”: Bana ne önerirsiniz?",
            "“I’d like a large pizza, please.”: Bir büyük boy pizza, lütfen.",
            "“Holy shit!”: Vay be!",
            "“Maybe some other time.”: Belki başka zaman.",
            "“Don’t piss me off!”: Beni kızdırma!",
            "“Sweet dreams.”: Tatlı rüyalar.",
            "“To be honest...”: Dürüst olmak gerekirse...",
            "“Get well soon.”: Çabuk iyileş / geçmiş olsun.",
            "“Don’t give up!”: Pes etme!",
            "“Just a moment.”: Bir dakika.",
            "“What’s your plan for tomorrow?”: Yarınki planın ne?",
            "“Are you for real?”: Sen şaka mısın?",
            "“Better late than never.”: Geç olsun güç olmasın.",
            "“Watch out!”: Dikkat et!",
            "“What if I refuse?”: Kabul etmezsem ne olur?",
            "“Suit yourself.”: Keyfin bilir.",
            "“Mind your own business.”: Kendi işine bak.",
            "“Let it go.”: Takma kafana / Bırak gitsin.",
            "“Cat got your tongue?”: Dilini mi yuttun?",
            "“It was my fault.”: Benim hatamdı.",
            "“My bad.”: Benim hatam.",
            "“Make it up to you.”: Sana telafi edeceğim.",
            "“Have fun!”: İyi eğlenceler!",
            " “Call it a day.”: Bugünlük bu kadar.",
            "“Don’t get me wrong.”: Beni yanlış anlama.",
            "“It is up to you.”: Sen bilirsin / sana kalmış.",
            "“Let’s get to the point.”: Sadede gelelim.",
            "“I’m an only child.”: Ben tek çocuğum.",
            "“You sound tired.”: Sesin yorgun geliyor.",
            "“You are one in a million!”: Sen milyonda birsin! (Eşsiz/Benzersiz)",
            "“Thanks though.”: Yine de teşekkürler.",
            "“I’m dead serious!”: Çok ciddiyim!",
            "“Don’t be childish!”: Çocuklaşma!",
            "“I hope so.”: Öyle umuyorum.",
            "“I’m confident.”: Kendime güveniyorum.",
            "“I’m broke!”: Beş parasızım!",
            "“So so.”: İdare eder / şöyle böyle.",
            "“Get lost!”: Kaybol!",
            "“I dabble in music.”: Amatör olarak müzik ile uğraşıyorum.",
            "“I pity you.”: Sana acıyorum.",
            "“Well said!”: İyi dedin!",
            "“That’s easy for you to say.”: Senin için söylemesi kolay.",
            "“No hard feeling.”: Alınmak yok / Darılmaca yok.",
            "“It\'s for your own good.”: Kendi iyiliğin için / İyiliğiniz için.",
            "“Keep your eyes peeled.”: Gözlerini dört aç.",
            "“Beats me!”: Beni aşar / Hiç bilmiyorum!",
            "“I’m not sure.”: Emin değilim.",
            "“I have no clue.”: Hiçbir fikrim yok.",
            "“I don’t know.”: Bilmiyorum.",
            "“I’m at the end of my rope.”: Sabrım taşmak üzere.",
            "“Make it snappy!”: Elini çabuk tut / Acele et!",
            "“Are you mocking me?”: Benimle alay mı ediyorsun?",
            "“You asked for it!”: Sen kaşındın!",
            "“Did you mind?”: Sakıncası var mı?",
            "“What am i supposed to do?”: Ne yapmam gerekiyor?",
            "“Keep your chin up!”: Başını dik tut!",
            "“What’s your rush?”: Ne bu acelen?",
            "“Make up your mind!”: Kararını ver!",
            "“I got stuck in traffic.”: Trafiğe takıldım.",
            "“You have not aged a day...”: Hiç yaşlanmamışsın...",
            "“Say when.”: Yeter de.",
            "“Don’t twist my words.”: Sözlerimi çarpıtma.",
            "“Don’t lecture me!”: Bana öğüt vermeyi bırak!",
            "“I feel blue.”: Üzgün hissediyorum.",
            "“Your fly is down.”: Dükkanın (fermuarın) açık kalmış.",
            "“Now you’re talking!”: Bana bunlarla gel!",
            "“I’m on a diet.”: Diyetteyim.",
            "“Don’t touch!”: Dokunma!",
            "“Sooner or later.”: Er ya da geç.",
            "“What’s the matter?”: Canını sıkan ne?",
            "“Well done!”: Aferin!",
            "“Therefore.”: Bu yüzden."});
            this.listBox2.Location = new System.Drawing.Point(12, 396);
            this.listBox2.Name = "listBox2";
            this.listBox2.SelectionMode = System.Windows.Forms.SelectionMode.MultiSimple;
            this.listBox2.Size = new System.Drawing.Size(396, 264);
            this.listBox2.TabIndex = 3;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(13F, 26F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1308, 743);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.textBox2);
            this.Controls.Add(this.listBox2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.textBox1);
            this.Controls.Add(this.listBox1);
            this.Font = new System.Drawing.Font("Times New Roman", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
            this.Margin = new System.Windows.Forms.Padding(5);
            this.Name = "Form1";
            this.Text = "Form1";
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.ListBox listBox1;
        private System.Windows.Forms.TextBox textBox1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.TextBox textBox2;
        private System.Windows.Forms.ListBox listBox2;
    }
}

